version: '3'
services:
  web:
    build: .
    volumes:
      - ./weblog:/app
    ports:
      - 8000:8000
    depends_on:
          - mongo
  mongo:
    image: mongo:3.6.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb

